In [45]:
import tensorflow as tf
print(tf.__version__)

2.21.0


In [46]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
model = Sequential()
model.add(Dense(64))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_39 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_40 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
import pandas as pd
data=pd.read_csv('Lab  winequality-red.csv')
y=data['quality']
x=data.drop('quality',axis=1)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(64,32), activation='tanh', max_iter=500)
model.fit(x_train, y_train)
print(model.score(x_test, y_test))


0.59375


In [49]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = model.predict(x_test)
confusion_matrix=confusion_matrix(y_test,y_pred)
print(confusion_matrix)

[[  0   0   1   0   0   0]
 [  1   0   8   1   0   0]
 [  0   0 103  24   3   0]
 [  0   0  47  75  10   0]
 [  0   0   2  28  12   0]
 [  0   0   0   3   2   0]]


In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(x_train.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(y_train.nunique(), activation='softmax'))
model.summary()
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.predict(x_train)

d:\internship 2026\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_41 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_42 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_43 (Dense)                │ (None, 6)              │           198 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,046 (11.90 KB)

 Trainable params: 3,046 (11.90 KB)

 Non-trainable params: 0 (0.00 B)

40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[1.03594765e-07, 4.32526367e-03, 1.27983685e-06, 2.18717878e-06,
        9.95425165e-01, 2.45939300e-04],
       [2.90515116e-13, 5.68693486e-06, 1.31120245e-11, 4.73591435e-13,
        9.99994159e-01, 2.03372579e-07],
       [1.65690407e-02, 3.98497991e-02, 2.17364207e-02, 8.31500888e-02,
        7.83308983e-01, 5.53855672e-02],
       ...,
       [3.75250579e-07, 1.07723456e-02, 3.06566767e-06, 1.24532221e-06,
        9.88321960e-01, 9.00998362e-04],
       [1.21075530e-02, 1.34121045e-01, 1.13627519e-02, 6.84987977e-02,
        7.16975749e-01, 5.69340736e-02],
       [1.52203701e-02, 1.65872231e-01, 1.77603569e-02, 2.98062526e-02,
        6.67566359e-01, 1.03774458e-01]], shape=(1279, 6), dtype=float32)

In [51]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(64, input_shape=(x_train.shape[1],), activation='relu'))
model.add(Dense(6, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
y_train_encoded = y_train - 3  # Adjusting labels to start from 0


d:\internship 2026\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [52]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(64, input_shape=(x_train.shape[1],), activation='relu'))
model.add(Dense(6, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
y_train=y_train-3
y_test=y_test-3
print(y_train)
print(y_test)

493     3
354     3
342     3
834     2
705     2
       ..
1130    3
1294    3
860     2
1459    4
1126    3
Name: quality, Length: 1279, dtype: int64
803     3
124     2
350     3
682     2
1326    3
       ..
1259    3
1295    2
1155    2
963     3
704     1
Name: quality, Length: 320, dtype: int64


d:\internship 2026\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [53]:
import pandas as pd
data=pd.read_csv('House_Rent_Dataset.csv')


In [54]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(32, input_shape=(x_train.shape[1],), activation='relu'))
model.add(Dense(1,activation='relu'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model = Sequential()
model.add(Dense(32, input_shape=(x_train.shape[1],), activation='relu'))
model.add(Dense(6, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train - 3, epochs=50, batch_size=32, validation_data=(x_test, y_test - 3))

Epoch 1/50


d:\internship 2026\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


InvalidArgumentError: Graph execution error:

Detected at node compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "d:\internship 2026\.venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>

  File "d:\internship 2026\.venv\Lib\site-packages\traitlets\config\application.py", line 1082, in launch_instance

  File "d:\internship 2026\.venv\Lib\site-packages\ipykernel\kernelapp.py", line 807, in start

  File "d:\internship 2026\.venv\Lib\site-packages\tornado\platform\asyncio.py", line 211, in start

  File "C:\Users\yramv\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 683, in run_forever

  File "C:\Users\yramv\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2050, in _run_once

  File "C:\Users\yramv\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run

  File "d:\internship 2026\.venv\Lib\site-packages\ipykernel\kernelbase.py", line 621, in shell_main

  File "d:\internship 2026\.venv\Lib\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell

  File "d:\internship 2026\.venv\Lib\site-packages\ipykernel\ipkernel.py", line 372, in execute_request

  File "d:\internship 2026\.venv\Lib\site-packages\ipykernel\kernelbase.py", line 834, in execute_request

  File "d:\internship 2026\.venv\Lib\site-packages\ipykernel\ipkernel.py", line 460, in do_execute

  File "d:\internship 2026\.venv\Lib\site-packages\ipykernel\zmqshell.py", line 665, in run_cell

  File "d:\internship 2026\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3170, in run_cell

  File "d:\internship 2026\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3225, in _run_cell

  File "d:\internship 2026\.venv\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner

  File "d:\internship 2026\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3447, in run_cell_async

  File "d:\internship 2026\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3688, in run_ast_nodes

  File "d:\internship 2026\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3748, in run_code

  File "C:\Users\yramv\AppData\Local\Temp\ipykernel_12708\100313117.py", line 14, in <module>

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 399, in fit

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 241, in function

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 154, in multi_step_on_iterator

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 125, in wrapper

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 134, in one_step_on_data

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 62, in train_step

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\trainers\trainer.py", line 419, in _compute_loss

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\trainers\trainer.py", line 387, in compute_loss

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\trainers\compile_utils.py", line 707, in __call__

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\trainers\compile_utils.py", line 732, in call

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\losses\loss.py", line 67, in __call__

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\losses\losses.py", line 34, in call

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\losses\losses.py", line 2359, in sparse_categorical_crossentropy

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\ops\nn.py", line 2216, in sparse_categorical_crossentropy

  File "d:\internship 2026\.venv\Lib\site-packages\keras\src\backend\tensorflow\nn.py", line 1438, in sparse_categorical_crossentropy

Received a label value of -1 which is outside the valid range of [0, 6).  Label values: -1 1 1 0 -1 -1 1 -1 -1 0 0 -1 -1 1 0 -1 0 0 -1 0 -1 -1 0 -1 -1 0 0 0 0 1 -1 2
	 [[{{node compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_multi_step_on_iterator_91684]

In [ ]:
import pandas as pd
data=pd.read_csv('House_Rent_Dataset.csv')
y=data['Rent']
x = data.drop(['Rent', 'Posted On', 'Floor', 'Area Locality'], axis=1)
import category_encoders as ce
encoder=ce.LeaveOneOutEncoder(return_df=True)
X=encoder.fit_transform(x,y)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(32, input_shape=(x_train.shape[1],), activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x_train,y_train,epoch=100,batch_size=32,validation_data=(x_test,y_test))

TypeError: TensorFlowTrainer.fit() got an unexpected keyword argument 'epoch'. Did you mean 'epochs'?

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential()
model.add(Dense(64,input_shape=(8,),activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')
model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_test, y_test))
model.predict(x_test[1:5])

Epoch 1/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6257911296.0000 - val_loss: 3092878592.0000
Epoch 2/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5716571136.0000 - val_loss: 3017160704.0000
Epoch 3/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5652117504.0000 - val_loss: 2921462784.0000
Epoch 4/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5608599552.0000 - val_loss: 2882790144.0000
Epoch 5/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5592379904.0000 - val_loss: 2853181696.0000
Epoch 6/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5576075264.0000 - val_loss: 2808733184.0000
Epoch 7/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5506098688.0000 - val_loss: 2824615168.0000
Epoch 8/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5497901568.0000 - val_loss: 2885859328.0000
Epoch 9/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5440365568.0000 - val_loss: 2722981120.0000
Epoch 10/100
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step -

array([[20435.066],
       [28032.41 ],
       [37147.207],
       [79486.016]], dtype=float32)